# Generated by Django 5.1.3 on 2024-12-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contact',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_image',
            field=models.ImageField(default='default.jpg', upload_to='media_file'),
        ),
        migrations.AddField(
            model_name='customer',
            name='next_of_kin',
            field=models.CharField(default='next_of_kin', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='name', max_length=150),
        ),
    ]
