# Generated by Django 5.1.3 on 2024-12-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_remove_customer_contact_customer_customer_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='assigned_customers',
        ),
    ]
