# Generated by Django 5.1.3 on 2024-12-26 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_alter_collection_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
