# Generated by Django 5.1.3 on 2024-12-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0006_customer_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='google_maps_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
