# Generated by Django 5.1.3 on 2024-12-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0008_collection_latitude_collection_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
