# Generated by Django 5.1.3 on 2024-12-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0009_collection_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='address',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='longitude',
        ),
    ]
