# Generated by Django 5.1.3 on 2024-12-26 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0010_remove_collection_address_remove_collection_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='google_maps_url',
        ),
    ]
